### ISSUE TITLE
How to allocate U128 to two U64?

### ISSUE THREAD

**Issue by iwojima** [calccrypto/uint128_t#5]
Hi Author,

Thank you for your contribution！i am trying to use your code to implement arithmetic for bigint，but i found the testcase abou it is too easy , i want to know how do you allocate U128 to two U64 ?   break down U128  into two binary number ？ or other way.

Thanks!

**Comment by calccrypto** [comment]
You can  do:

```c++
uint128_t value = /* some value */;
uint64_t upper = value >> 64;
uint64_t lower = value & 0xffffffffffffffffULL;
```

You can also get the values directly:

```c++
uint128_t value = /* some value */;
uint64_t upper = value.upper();
uint64_t lower = value.lower();
```

**Comment by iwojima** [comment]
Hi Jason:

Thank you for your help. i had followed your way to try disassembling of u64 , as below:

uint64_t u64 = 18446744073709551615;
upper (u64 >> 32)                    = 4294967295
lower (u64 &  0xFFFFFFFFULL) = 4294967295

4294967295 is the MAX value of u32 , so the result meet expectation ，but the result of u128 is invalid , i use the MAX value of u128(340282366920938463463374607431768211455) , as below:

upper (340282366920938463463374607431768211455 >> 64)                                  = 0
lower (340282366920938463463374607431768211455 & 0xFFFFFFFFFFFFFFFFULL)) = 18446744073709551615

it look like " >>" operator doesn't support the operation ， did you also find the issue in your environment ? or did you open some compilation options ？

Thanks！

**Comment by calccrypto** [comment]
Did you hardcode `340282366920938463463374607431768211455` into your code? If so, that wouldn't be allowed, since `uint128_t` is not a standard type (otherwise, there would be no point in having this library). `340282366920938463463374607431768211455` would be treated as a literal and cast into the largest standard type there is, aka `int64_t/long long int` ([since the value is in decimal, with no suffixes](https://en.cppreference.com/w/cpp/language/integer_literal)), meaning the first 64 bits would be ignored, which is what you are seeing. 

I did define [a few constants I thought would be useful in the header](https://github.com/calccrypto/uint128_t/blob/master/uint128_t.h#L337). `uint128_max` seems to be what you want.

```
uint128_t max = uint128_max;          // 340282366920938463463374607431768211455
uint64_t upper = max >> 64;           // 18446744073709551615
uint64_t lower = max & (uint64_t) -1; // 18446744073709551615
```

GCC does have a [`__int128`](https://gcc.gnu.org/onlinedocs/gcc-4.8.1/gcc/_005f_005fint128.html#_005f_005fint128) extension, but you still would not be able to hard code `340282366920938463463374607431768211455`, as `There is no support in GCC for expressing an integer constant of type __int128 for targets with long long integer less than 128 bits wide.`

**Comment by iwojima** [comment]
I understand, Thanks!
